import {test,expect} from '@playwright/test';
test('studio door faces the square and approaching activates entry',async({page})=>{
 test.setTimeout(180000);
 await page.goto('/playable-3d/');
 await expect(page.locator('#loading')).toBeHidden({timeout:120000});
 await page.locator('#home-destination').click();
 await expect(page.locator('#interact')).toBeVisible();
 await expect(page.locator('#interact')).toContainText('Open Avatar Studio');
 await page.locator('#scene').focus();
 await page.keyboard.down('s');
 await expect(page.locator('#interact')).toBeHidden({timeout:15000});
 await page.keyboard.up('s');
 await page.keyboard.down('w');
 await expect(page.locator('#interact')).toBeVisible({timeout:15000});
 await page.keyboard.up('w');
 await page.screenshot({path:test.info().outputPath('studio-door-approach.png')});
 await page.keyboard.press('e');
 await expect(page.locator('#studio-panel')).toBeVisible();
 await expect(page.locator('#interact')).toBeHidden();
});
