import {test,expect} from '@playwright/test';
test.setTimeout(120000);
const entry='/playable-3d/';
async function ready(page,id){await page.waitForFunction(id=>JSON.parse(document.querySelector('#diagnostics').value||'{}').echo?.helper===id,id,{timeout:90000});}
async function choose(page,id){await page.locator(`[name="guidance"][value="${id}"]`).check();await page.locator('[data-continue]').click();}
for(const width of [1280,390])for(const mode of ['none','journal'])test(`${mode} at ${width}: no models, guidance, persistence`,async({page},info)=>{
 await page.setViewportSize({width,height:844});const requests=[];page.on('request',r=>{if(/\/helpers\/.*\.glb/.test(r.url()))requests.push(r.url());});await page.goto(entry);await expect(page.locator('#helper-picker')).toBeVisible();await expect(page.locator('.helper-card')).toHaveCount(0);await page.screenshot({path:info.outputPath('opening.png')});await choose(page,mode);await ready(page,mode);expect(requests).toEqual([]);await expect(page.locator('#echo-cue')).toBeHidden();await page.locator('#guidance-help').click();await expect(page.locator('#echo-dialogue')).toBeVisible();await expect(page.locator('[data-message]')).not.toContainText('I’m');await page.locator('[data-next]').click();await page.locator('[data-next]').click();await page.locator('[data-action]').click();await expect(page.locator('[data-message]')).toContainText('not available');await page.locator('[data-next]').click();await page.keyboard.press('Escape');await page.screenshot({path:info.outputPath('world.png')});await page.reload();await ready(page,mode);await expect(page.locator('#helper-picker')).not.toBeVisible();await page.locator('#guidance-help').click();await expect(page.locator('#echo-dialogue h2')).toHaveText('Put learning into practice');expect(requests).toEqual([]);
});
test('switching preserves progress, chooses old creature only on request, without extra downloads',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('ce-helper-v1:avery','moss'));const requests=[];page.on('request',r=>{if(/\/helpers\/.*\.glb/.test(r.url()))requests.push(r.url().split('/').pop());});await page.goto(entry);await choose(page,'none');await ready(page,'none');await page.locator('#guidance-help').click();await page.locator('[data-next]').click();await page.keyboard.press('Escape');await page.locator('#choose-helper').click();await page.locator('[name="guidance"][value="creature"]').check();await expect(page.locator('[name="helper"][value="moss"]')).toBeChecked();expect(requests).toEqual([]);await page.locator('[data-continue]').click();await ready(page,'moss');await page.waitForFunction(()=>JSON.parse(document.querySelector('#diagnostics').value).echo.helperStatus==='ready');expect(requests).toEqual(['moss.glb']);await page.locator('#guidance-help').click();await expect(page.locator('#echo-dialogue h2')).toHaveText('A different kind of year');await page.keyboard.press('Escape');await page.locator('#choose-helper').click();await choose(page,'journal');await ready(page,'journal');await expect(page.locator('#echo-cue')).toBeHidden();await page.locator('#guidance-help').click();await expect(page.locator('#echo-dialogue h2')).toHaveText('A different kind of year');expect(requests).toEqual(['moss.glb']);
});
test('switching away from a pending creature keeps it disabled after the response',async({page})=>{
 let release;const held=new Promise(resolve=>release=resolve);const timer=setTimeout(()=>release(),10000);await page.route('**/helpers/moss.glb',async route=>{await held;try{await route.continue();}catch{}});
 await page.goto(entry);await page.locator('[name="guidance"][value="creature"]').check();await page.locator('[name="helper"][value="moss"]').check();await page.locator('[data-continue]').click();await ready(page,'moss');await page.locator('#choose-helper').click();await choose(page,'none');await ready(page,'none');release();clearTimeout(timer);await page.waitForFunction(()=>JSON.parse(document.querySelector('#diagnostics').value).echo.helperStatus==='disabled');await expect(page.locator('#echo-cue')).toBeHidden();await page.locator('#guidance-help').click();await expect(page.locator('#echo-dialogue')).toBeVisible();
});
