import {test,expect} from './campus-fixtures.js';
async function fixture(page,visible=true){
 await page.route('**/graphics-test',r=>r.fulfill({contentType:'text/html',body:'<html><head><script type="importmap">{"imports":{"three":"/playable-3d/vendor/three/build/three.module.js","three/addons/":"/playable-3d/vendor/three/examples/jsm/"}}</script></head><body style="margin:0"><main id="experience"><canvas id="scene"></canvas></main></body></html>'}));
 await page.goto('/graphics-test');await page.evaluate(async(visible)=>{const T=await import('three');const {createNightMarket}=await import('/playable-3d/night-market.js');window.market=createNightMarket({storage:{getItem:()=>null,setItem(){}},onPause(){},onClose(){},onExit(){}});window.T=T;window.camera=new T.PerspectiveCamera(48,1280/844,.1,100);camera.position.set(13,9,18);camera.lookAt(0,1,-2);window.renderer=new T.WebGLRenderer({canvas:document.querySelector('canvas'),antialias:true});renderer.setSize(1280,844);renderer.shadowMap.enabled=true;renderer.toneMapping=T.ACESFilmicToneMapping;if(visible)market.setVisible(true);},visible);
}
test('all character copies load, animate independently and render in the market',async({page})=>{
 test.setTimeout(60000);await page.setViewportSize({width:1280,height:844});const errors=[];page.on('pageerror',e=>errors.push(e.message));await fixture(page,false);expect(await page.evaluate(()=>performance.getEntriesByType('resource').filter(r=>r.name.includes('/market-npcs/')).length)).toBe(0);await page.evaluate(()=>market.setVisible(true));
 await expect.poll(()=>page.evaluate(()=>market.snapshot().visuals.ready),{timeout:30000}).toBe(14);
 const result=await page.evaluate(()=>{market.update(.016,1,camera);renderer.render(market.scene,camera);const skinned=[];market.scene.traverse(o=>{if(o.isSkinnedMesh)skinned.push(o);});return {queueFacing:market.scene.children.filter(o=>o.name.startsWith('Market actor /')).slice(2,8).map(a=>a.children.at(-1).rotation.y),count:skinned.length,bones:skinned.map(o=>o.skeleton.bones[0].uuid),finite:skinned.every(o=>o.skeleton.boneMatrices.every(Number.isFinite)),feet:skinned.map(o=>{let a=o;while(a&&!a.name.startsWith('Market actor /'))a=a.parent;return new T.Box3().setFromObject(o,true).min.y-a.position.y;}),heights:skinned.map(o=>{o.skeleton.update();return new T.Box3().setFromObject(o,true).getSize(new T.Vector3()).y;}),calls:renderer.info.render.calls,triangles:renderer.info.render.triangles};});
 expect(result.count).toBe(14);for(const angle of result.queueFacing)expect(angle).toBeCloseTo(Math.PI);expect(new Set(result.bones).size).toBe(14);expect(result.finite).toBe(true);for(const foot of result.feet){expect(Math.abs(foot)).toBeLessThan(.12);}for(const height of result.heights){expect(height).toBeGreaterThan(1.5);expect(height).toBeLessThan(1.95);}expect(errors).toEqual([]);const changed=await page.evaluate(()=>{const a=market.scene.getObjectByName('Market actor / customer-a');let mesh;a.traverse(o=>{if(o.isSkinnedMesh)mesh=o;});const before=mesh.skeleton.bones.map(b=>b.quaternion.toArray().join(','));for(let i=0;i<30;i++){a.position.x+=.02;market.update(.016,i*.016,camera);}return mesh.skeleton.bones.filter((b,i)=>b.quaternion.toArray().join(',')!==before[i]).length;});expect(changed).toBeGreaterThan(3);console.log('MARKET_GRAPHICS',result);
 await page.screenshot({path:'/tmp/market-graphics-overview.png'});
 await page.evaluate(()=>{camera.position.set(1,2.3,-.8);camera.lookAt(0,1.3,-5.8);for(let i=0;i<20;i++)market.update(.016,i*.016,camera);renderer.render(market.scene,camera);});await page.screenshot({path:'/tmp/market-graphics-juniper.png'});await page.evaluate(()=>{camera.position.set(8,2.5,.5);camera.lookAt(8,1.6,-5);renderer.render(market.scene,camera);});await page.screenshot({path:'/tmp/market-stage-equipment.png'});
});
test('a missing Sam keeps the shift accessible and retries on re-entry',async({page})=>{
 test.setTimeout(60000);await page.route('**/market-npcs/sam.glb',r=>r.abort());await fixture(page);
 await expect.poll(()=>page.evaluate(()=>market.snapshot().visuals.assets.sam)).toBe('fallback');await page.evaluate(()=>market.interaction({x:0,z:-3.6}).action());await expect(page.getByRole('button',{name:'Take the shift',exact:true})).toBeVisible();await page.getByRole('button',{name:'Take the shift',exact:true}).click();
 await expect.poll(()=>page.evaluate(()=>Object.values(market.snapshot().visuals.assets).filter(v=>v==='ready').length),{timeout:30000}).toBe(6);
 await page.unroute('**/market-npcs/sam.glb');await page.evaluate(()=>{market.setVisible(false);market.setVisible(true);});await expect.poll(()=>page.evaluate(()=>market.snapshot().visuals.ready),{timeout:20000}).toBe(14);
});
