import {test} from './campus-fixtures.js';
import fs from 'node:fs';
import assert from 'node:assert/strict';

// Test-only access is appended to the intercepted module; no debug hook ships.
test('teachers: reactions, bounded collision, lazy loading, mobile and recovery',async({page:p},testInfo)=>{
 test.setTimeout(240000);await p.setViewportSize({width:1440,height:1000});
const requests=[],errors=[];p.on('request',r=>requests.push(r.url()));p.on('pageerror',e=>errors.push(e.message));await p.route('**/app.js?*',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text())+'\nwindow.__npcTest={get teachers(){return teachers},get worlds(){return worlds},get actor(){return actor},get camera(){return camera},get renderer(){return renderer},updateCamera,updateInteraction};'});});
await p.goto('http://127.0.0.1:4273/playable-3d/');await p.waitForFunction(()=>document.querySelector('#loading').hidden,null,{timeout:120000});await p.waitForTimeout(600);assert.equal(requests.filter(u=>/mr-(middleton|psandodakis).*glb|teacher-npc.js|\/studio.js|OrbitControls/.test(u)).length,0);const cold={unrequestedNPCAndStudio:true};
await p.goto('http://127.0.0.1:4273/playable-3d/?view=teachers');await p.waitForFunction(()=>window.__npcTest?.teachers.length===2,null,{timeout:60000});await p.screenshot({path:testInfo.outputPath('teachers-campus.png')});
const cycles=[];
for(const [id,actions]of [['middleton',['wave','laugh','look']],['psandodakis',['nod','cheer','clap','dance']]]){
 for(const action of actions){
  await p.evaluate(id=>{const t=window.__npcTest,n=t.teachers.find(n=>n.id===id),r=n.root.position;t.worlds.teleport(false,r.x,r.z+3.2);t.actor.model.position.copy(t.worlds.position(false));t.updateCamera(1,true);t.updateInteraction();},id);
  await p.getByRole('button',{name:new RegExp('Say hello to '+(id==='middleton'?'Mr Middleton':'Mr Psandodakis'))}).click();
  await p.waitForFunction(({id,action})=>window.__npcTest.teachers.find(n=>n.id===id).snapshot().state===action,{id,action});
  const result=await p.evaluate(({id,action})=>{const t=window.__npcTest,n=t.teachers.find(n=>n.id===id),before=n.snapshot().reactions;n.react(t.actor.model.position);const repeatedIgnored=n.snapshot().reactions===before;for(let i=0;i<80;i++){for(const npc of t.teachers){npc.fixedUpdate(1/60,t.actor.model.position);npc.update(1/60,t.actor.model.position);}t.worlds.townPhysics.world.step();}return{id,action,repeatedIgnored,snapshot:n.snapshot()};},{id,action});assert(result.repeatedIgnored);cycles.push(result);
  if(action==='dance'||action==='wave'){await p.screenshot({path:testInfo.outputPath(`teachers-${id}-${action}.png`)});}
  await p.evaluate(id=>{const t=window.__npcTest,n=t.teachers.find(n=>n.id===id);for(let i=0;i<1200&&n.snapshot().state!=='idle';i++){for(const npc of t.teachers){npc.fixedUpdate(1/60,t.actor.model.position);npc.update(1/60,t.actor.model.position);}t.worlds.townPhysics.world.step();}},id);
 }
}
const physics=await p.evaluate(async()=>{const t=window.__npcTest,w=t.worlds.townPhysics.world,R=(await import('/playable-3d/vendor/rapier/rapier.mjs')).default;const stats=t.teachers.map(n=>({id:n.id,maxEllipse:0,walk:0,idle:0,maxStep:0,last:n.snapshot().position}));let minimumSeparation=Infinity;for(let i=0;i<18000;i++){for(const n of t.teachers)n.fixedUpdate(1/60,{x:-4,z:-49});w.step();for(let k=0;k<t.teachers.length;k++){const n=t.teachers[k],a=stats[k],s=n.snapshot(),[x,y,z]=s.position;n.update(1/60,{x:-4,z:-49});a.maxEllipse=Math.max(a.maxEllipse,((x+4)/8)**2+((z+54)/4)**2);a.maxStep=Math.max(a.maxStep,Math.hypot(x-a.last[0],z-a.last[2]));a.last=s.position;if(s.state==='walk')a.walk++;if(s.state==='idle')a.idle++;if(!Number.isFinite(y)||Math.abs(y)>.2)throw Error('Ground contact lost');}minimumSeparation=Math.min(minimumSeparation,t.teachers[0].root.position.distanceTo(t.teachers[1].root.position));}
const trapped=t.teachers[0],[x,y,z]=trapped.snapshot().position,walls=[];for(const [dx,dz,sx,sz]of [[-.8,0,.1,2],[.8,0,.1,2],[0,-.8,2,.1],[0,.8,2,.1]])walls.push(w.createCollider(R.ColliderDesc.cuboid(sx,2,sz).setTranslation(x+dx,2,z+dz)));w.step();let escape=0;for(let i=0;i<3600;i++){for(const n of t.teachers)n.fixedUpdate(1/60,{x:-4,z:-49});w.step();const s=trapped.snapshot();escape=Math.max(escape,Math.abs(s.position[0]-x),Math.abs(s.position[2]-z));}walls.forEach(c=>w.removeCollider(c,true));return{stats,minimumSeparation,escape};});console.log('PHYSICS',JSON.stringify(physics));for(const s of physics.stats){assert(s.maxEllipse<=1.0001);assert(s.walk>0&&s.idle>0);assert(s.maxStep<.02);}assert(physics.minimumSeparation>.5);assert(physics.escape<.6);
await p.goto('http://127.0.0.1:4273/playable-3d/?view=mr-psandodakis');await p.waitForFunction(()=>window.__npcTest?.teachers.length===2);await p.setViewportSize({width:390,height:844});await p.waitForTimeout(300);const point=await p.evaluate(()=>{const t=window.__npcTest,n=t.teachers[1],v=n.root.position.clone();v.y+=1.3;v.project(t.camera);const r=document.querySelector('#scene').getBoundingClientRect();return{x:r.left+(v.x+1)/2*r.width,y:r.top+(1-v.y)/2*r.height}});await p.mouse.click(point.x,point.y);await p.waitForFunction(()=>window.__npcTest.teachers[1].snapshot().state==='nod');await p.screenshot({path:testInfo.outputPath('teachers-mobile.png')});
await p.locator('#studio-view').click();await p.waitForFunction(()=>!document.querySelector('#studio-panel').hidden);const before=await p.evaluate(()=>window.__npcTest.teachers.map(n=>n.snapshot()));await p.waitForTimeout(600);assert.deepEqual(await p.evaluate(()=>window.__npcTest.teachers.map(n=>n.snapshot())),before);await p.locator('#town-view').click();await p.waitForFunction(()=>document.querySelector('#studio-panel').hidden);assert(!await p.getByLabel('Body',{exact:true}).locator('option').allTextContents().then(a=>a.some(x=>/Middleton|Psandodakis/.test(x))));assert.deepEqual(errors,[]);
// An optional asset failure cannot block play or the other teacher, and retries on return.
let fail=true;await p.route('**/mr-psandodakis-20260917.glb',r=>fail?r.abort():r.continue());await p.goto('http://127.0.0.1:4273/playable-3d/?view=teachers');await p.waitForFunction(()=>window.__npcTest?.teachers.length===1);await p.waitForTimeout(500);assert.equal(await p.locator('#loading').evaluate(e=>e.hidden),true);fail=false;await p.evaluate(()=>{const t=window.__npcTest;t.worlds.teleport(false,-7,23.3);t.actor.model.position.copy(t.worlds.position(false));});await p.waitForTimeout(400);await p.evaluate(()=>{const t=window.__npcTest;t.worlds.teleport(false,-4,-49);t.actor.model.position.copy(t.worlds.position(false));});await p.waitForFunction(()=>window.__npcTest.teachers.length===2);
const result={cold,cycles,physics,mobileTap:true,studioPaused:true,failureIsolatedAndRetryPassed:true,errors};fs.writeFileSync(testInfo.outputPath('teachers-validation.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
});
