import {test,expect} from './campus-fixtures.js';
for(const width of [1280,390])test(`plan to visible trial has a clear next step at ${width}`,async({page},info)=>{
 test.setTimeout(90000);await page.setViewportSize({width,height:844});
 await page.route('**/app.js?*',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text())+'\nwindow.trialReview=()=>({market:nightMarket,camera});'});});
 await page.goto('/playable-3d/?experience=sunday-markets&market-review=1',{waitUntil:'domcontentloaded'});await expect(page.locator('#loading')).toBeHidden({timeout:30000});
 const visit=(x,z)=>page.evaluate(([x,z])=>trialReview().market.interaction({x,z}).action(),[x,z]);
 await visit(0,-3.6);await page.getByRole('button',{name:'Take the shift',exact:true}).click();
 await visit(4.2,-1.8);await page.getByLabel('Sign wording',{exact:true}).selectOption('pickup');await page.getByLabel('Sign position',{exact:true}).selectOption('approach');await page.getByRole('button',{name:'Set this arrangement',exact:true}).click();
 await expect(page.locator('#market-dialog')).toContainText('Then talk it through with Mara');await page.getByRole('button',{name:'Back to the market',exact:true}).click();
 const sign=await page.evaluate(()=>{const root=trialReview().market.scene.getObjectByName('Juniper / movable collection sign');return root.children.filter(c=>c.geometry?.type==='PlaneGeometry').map(c=>({z:c.position.z,rotation:c.rotation.y,sprite:c.isSprite||false}));});
 expect(sign).toHaveLength(2);expect(sign.every(s=>Math.abs(s.z)>.05&&!s.sprite)).toBe(true);expect(sign[1].rotation).toBeCloseTo(Math.PI);
 await expect(page.locator('#market-objective')).toContainText('go and watch the queue');
 await visit(-3,4);await expect(page.locator('#market-dialog')).toContainText('Test this arrangement');await page.getByRole('button',{name:'Start the test',exact:true}).click();
 const positions=()=>page.evaluate(()=>trialReview().market.scene.children.filter(o=>o.name.startsWith('Market actor / customer')).slice(0,6).map(o=>o.position.toArray()));const start=await positions();
 await expect.poll(async()=>Math.max(...(await positions()).map((p,i)=>Math.hypot(p[0]-start[i][0],p[2]-start[i][2]))),{timeout:6000}).toBeGreaterThan(1);
 await expect(page.locator('#market-dialog')).not.toBeVisible();await page.screenshot({path:info.outputPath(`trial-moving-${width}.png`)});
 await expect(page.locator('#market-dialog')).toContainText('Trial 1 / what happened',{timeout:12000});
 await expect(page.locator('#market-dialog')).toContainText('4 of 4 phone customers');
 const result=await page.evaluate(()=>trialReview().market.snapshot());expect(result.trials).toHaveLength(1);expect(result.wallet).toBe(0);expect(result.paid).toBe(false);expect(result.shared).toBe(false);
 await page.getByRole('button',{name:'Record that I checked this result',exact:true}).click();
 await page.getByRole('button',{name:'Go and talk it through with Mara',exact:true}).click();
 await visit(0,-3.6);await expect(page.locator('#market-dialog')).toContainText('Name what you practised');
 await page.getByRole('button',{name:'Back to the market',exact:true}).click();await expect(page.locator('#market-test')).toBeHidden();
});
