import test from 'node:test';import assert from 'node:assert/strict';
import {empty,project,KEY} from '../economy-lab/economy.mjs';
import {MILESTONES,awardExploration,createExplorer} from '../economy-lab/exploration.mjs';
test('seven first visits add exactly $700, repeat visits do not pay, and purchases remain possible',()=>{let d=empty();for(const key of Object.keys(MILESTONES))d=awardExploration(d,key);const s=project(d);assert.equal(s.cash,170000);assert.equal(s.explorationRewards,70000);assert.equal(s.explored.length,7);for(const key of Object.keys(MILESTONES))assert.equal(awardExploration(d,key),d);assert.equal(s.log.length,7);assert.equal(s.tax,0);});
test('unknown milestones cannot award money',()=>assert.throws(()=>awardExploration(empty(),'made-up')));
test('successful save reloads and only notifies once',async()=>{let raw=null;const notes=[];const storage={getItem:()=>raw,setItem:(key,value)=>{assert.equal(key,KEY);raw=value;}};const visit=createExplorer({storage,notify:t=>notes.push(t)});await visit('shop');await visit('shop');await createExplorer({storage,notify:t=>notes.push(t)})('shop');assert.equal(project(JSON.parse(raw)).cash,110000);assert.equal(notes.length,1);});
test('failed storage cannot report a reward or alter persisted state',async()=>{const notes=[];const visit=createExplorer({storage:{getItem:()=>null,setItem:()=>{throw Error('quota');}},notify:t=>notes.push(t)});assert.equal(await visit('shop'),false);assert.match(notes[0],/not saved/);});
test('review uses no storage and repeat visits are idempotent',async()=>{const notes=[];const visit=createExplorer({review:true,storage:{getItem:()=>{throw Error('must not read');},setItem:()=>{throw Error('must not write');}},notify:t=>notes.push(t)});await visit('chapel');await visit('chapel');assert.equal(notes.length,1);assert.match(notes[0],/review only/);});
test('corrupt saved data is never replaced',async()=>{let writes=0;const visit=createExplorer({storage:{getItem:()=>'{broken',setItem:()=>writes++}});assert.equal(await visit('market'),false);assert.equal(writes,0);});
