import {HELPERS,helperFor,createHelperStore} from './helper-state.js?v=guidance-20260928';
export function createHelperPicker({profile,onOpen=()=>{},onChange=()=>{}}){
 let storage;try{storage=localStorage;}catch{}
 const store=createHelperStore(storage),dialog=document.createElement('dialog');dialog.id='helper-picker';dialog.setAttribute('aria-labelledby','helper-heading');
 dialog.innerHTML='<form method="dialog"><small>YOUR CAREER EMPIRE JOURNEY</small><h1 id="helper-heading">How would you like to find your way?</h1><p>The same guidance is available with every option. You can change this any time.</p><div class="guidance-options"><label><input type="radio" name="guidance" value="none"><span><strong>No companion</strong><small>Explore independently. Help is here whenever you need it.</small></span></label><label><input type="radio" name="guidance" value="creature"><span><strong>Friendly creature</strong><small>Pick a character to guide you.</small></span></label><label><input type="radio" name="guidance" value="journal"><span><strong>Phone / journal</strong><small>Keep your next steps and useful information in one place.</small></span></label></div><section data-creatures hidden><h2>Choose your creature</h2><div class="helper-grid"></div></section><p id="helper-save-note">Your preference stays with this character in this browser.</p><footer><button type="button" data-cancel>Cancel</button><button type="submit" data-continue>Continue without a companion</button></footer></form>';
 document.body.append(dialog);let selected='echo',mode='none',target=null,resolve=null,required=false,built=false;
 const grid=dialog.querySelector('.helper-grid'),go=dialog.querySelector('[data-continue]'),cancel=dialog.querySelector('[data-cancel]');
 function render(){dialog.querySelector('[data-creatures]').hidden=mode!=='creature';if(mode==='creature'&&!built){built=true;for(const h of HELPERS){const label=document.createElement('label');label.className='helper-card';const input=document.createElement('input');input.type='radio';input.name='helper';input.value=h.id;const img=document.createElement('img');img.src=h.portrait;img.alt='';img.width=192;img.height=192;img.decoding='async';const name=document.createElement('span');name.textContent=h.name;label.append(input,img,name);grid.append(label);input.onchange=()=>{selected=h.id;render();};}}if(built)dialog.querySelector(`input[name="helper"][value="${selected}"]`).checked=true;go.textContent=mode==='creature'?'Continue with '+helperFor(selected).name:mode==='journal'?'Continue with phone / journal':'Continue without a companion';}
 for(const input of dialog.querySelectorAll('[name="guidance"]'))input.onchange=()=>{mode=input.value;render();};
 function finish(value){dialog.close();const done=resolve;resolve=null;done?.(value);}
 dialog.querySelector('form').onsubmit=e=>{e.preventDefault();const choice=mode==='creature'?selected:mode;store.write(target,choice);onChange(helperFor(choice),store.persistent);finish(choice);};
 cancel.onclick=()=>finish(null);dialog.oncancel=e=>{if(required)e.preventDefault();else finish(null);};
 return {store,selected:()=>helperFor(store.read(profile())||'none'),open:()=>dialog.open,
 choose(force=false){if(dialog.open)return Promise.resolve(null);const saved=store.read(profile());if(saved&&!force)return Promise.resolve(saved);target=profile();const old=store.legacy(target);selected=HELPERS.some(h=>h.id===saved)?saved:HELPERS.some(h=>h.id===old)?old:'echo';mode=saved==='journal'?'journal':saved&&saved!=='none'?'creature':'none';required=!saved;cancel.hidden=required;dialog.querySelector(`[name="guidance"][value="${mode}"]`).checked=true;render();onOpen();dialog.showModal();return new Promise(r=>resolve=r);}};
}
