import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFExporter} from './vendor/exporters/GLTFExporter.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {EffectComposer} from './vendor/postprocessing/EffectComposer.js';
import {RenderPass} from './vendor/postprocessing/RenderPass.js';
import {SSAOPass} from './vendor/postprocessing/SSAOPass.js';
import {OutputPass} from './vendor/postprocessing/OutputPass.js';
import {buildExterior,VIEWS,DOORS,canWalk} from './model.js';

const canvas=document.querySelector('#scene'),renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,preserveDrawingBuffer:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.outputColorSpace=T.SRGBColorSpace;
const scene=new T.Scene();scene.background=new T.Color(0xcbd8da);scene.fog=new T.Fog(0xcbd8da,42,95);
const camera=new T.PerspectiveCamera(48,innerWidth/innerHeight,.08,140),controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.08;controls.maxPolarAngle=Math.PI*.49;controls.minDistance=2;controls.maxDistance=45;controls.target.set(0,2,0);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const ao=new SSAOPass(scene,camera,innerWidth,innerHeight,12);ao.kernelRadius=.55;ao.minDistance=.002;ao.maxDistance=.08;composer.addPass(ao);composer.addPass(new OutputPass());composer.renderTarget1.samples=4;composer.renderTarget2.samples=4;renderer.info.autoReset=false;
const hemi=new T.HemisphereLight(0xd4e5f2,0x827765,1.1);scene.add(hemi);const sun=new T.DirectionalLight(0xffdfac,3.3);sun.position.set(-17,18,7);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-22,right:22,top:22,bottom:-22,near:1,far:70});sun.shadow.bias=-.00015;sun.shadow.normalBias=.025;sun.shadow.radius=3;scene.add(sun);scene.add(sun.target);
const pmrem=new T.PMREMGenerator(renderer),env=pmrem.fromScene(new RoomEnvironment(),.04);scene.environment=env.texture;scene.environmentIntensity=.2;
let model,walking=false,currentView='arrival',yaw=0,pitch=0,drag=null,frameCount=0,frameStart=performance.now(),fps=0,elapsed=0;const keys=new Set(),position=new T.Vector3(0,1.68,11),last=new T.Clock();
const status=document.querySelector('#loading');
function applyView(name){walking=false;document.querySelector('#walk').setAttribute('aria-pressed','false');document.querySelector('#movement').hidden=true;controls.enabled=true;controls.enablePan=true;const view=VIEWS[name];camera.position.fromArray(view.position);controls.target.fromArray(view.target);controls.update();currentView=name;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.querySelector('#hint').textContent='Drag to orbit · scroll to zoom · choose a viewpoint';document.querySelector('#place').hidden=true;}
function toggleWalk(){walking=!walking;keys.clear();document.querySelector('#walk').setAttribute('aria-pressed',String(walking));document.querySelector('#movement').hidden=!walking;controls.enabled=!walking;document.querySelector('#place').hidden=true;if(walking){position.set(0,1.68,11);yaw=0;pitch=0;document.querySelectorAll('[data-view]').forEach(b=>b.classList.remove('active'));document.querySelector('#hint').textContent='WASD / arrows to walk · drag to look · Esc to orbit';}else applyView(currentView);}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>applyView(b.dataset.view)));
document.querySelector('#walk').addEventListener('click',toggleWalk);
document.querySelector('#light').addEventListener('change',e=>{const warm=e.target.value==='warm';sun.color.set(warm?0xffe1af:0xfff5e7);sun.intensity=warm?3.6:3;sun.position.set(warm?-15:5,warm?23:32,warm?12:15);hemi.intensity=warm?1.1:1.6;renderer.toneMappingExposure=warm?1.12:1.02;});
document.querySelector('#quality').addEventListener('change',e=>{const q=e.target.value;renderer.setPixelRatio(q==='high'?Math.min(devicePixelRatio,2):q==='low'?1:Math.min(devicePixelRatio,1.5));ao.enabled=q!=='low';sun.shadow.mapSize.set(q==='high'?4096:q==='low'?1024:2048,q==='high'?4096:q==='low'?1024:2048);sun.shadow.map?.dispose();sun.shadow.map=null;resize();});
document.querySelector('#details').addEventListener('click',e=>{const el=document.querySelector('#stats');el.hidden=!el.hidden;e.target.setAttribute('aria-expanded',String(!el.hidden));});
const keyMap={KeyW:'forward',ArrowUp:'forward',KeyS:'back',ArrowDown:'back',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right'};
addEventListener('keydown',e=>{if(e.target.matches('select,input,textarea'))return;if(e.code==='Escape'&&walking)toggleWalk();if(walking&&keyMap[e.code]){e.preventDefault();keys.add(keyMap[e.code]);}});addEventListener('keyup',e=>keys.delete(keyMap[e.code]));addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>keys.clear());
for(const b of document.querySelectorAll('[data-move]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.move);});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys.delete(b.dataset.move));}
canvas.addEventListener('pointerdown',e=>{if(walking){canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY};}});canvas.addEventListener('pointermove',e=>{if(walking&&drag){yaw-=(e.clientX-drag.x)*.004;pitch=Math.max(-.7,Math.min(.6,pitch-(e.clientY-drag.y)*.003));drag={x:e.clientX,y:e.clientY};}});for(const event of ['pointerup','pointercancel'])canvas.addEventListener(event,()=>drag=null);
function resize(){camera.aspect=innerWidth/innerHeight;camera.fov=innerWidth<720?58:48;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setPixelRatio(renderer.getPixelRatio());composer.setSize(innerWidth,innerHeight);ao.setSize(Math.round(innerWidth*.75),Math.round(innerHeight*.75));}addEventListener('resize',resize);resize();
document.querySelector('#export').addEventListener('click',async e=>{const button=e.currentTarget;button.disabled=true;button.textContent='Preparing model…';try{
 const output=new T.Group();output.name=model.root.name;
 model.root.traverse(o=>{if(!o.isMesh)return;if(o.isInstancedMesh){for(let i=0;i<o.count;i++){const matrix=new T.Matrix4();o.getMatrixAt(i,matrix);const mesh=new T.Mesh(o.geometry,o.material);mesh.applyMatrix4(matrix);mesh.name=o.name+' '+i;output.add(mesh);}}else{const mesh=new T.Mesh(o.geometry,o.material);mesh.applyMatrix4(o.matrixWorld);mesh.name=o.name;output.add(mesh);}});
 const glb=await new GLTFExporter().parseAsync(output,{binary:true,onlyVisible:true});
 const saved=await fetch('/ecc-export.glb',{method:'POST',headers:{'Content-Type':'model/gltf-binary'},body:glb});if(!saved.ok)throw Error('Use the included local preview server to save the model.');
 await fetch('/ecc-layout.json',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({doors:DOORS,views:VIEWS,obstacles:model.obstacles,plantInstances:model.plantInstances,triangles:renderer.info.render.triangles,draws:renderer.info.render.calls,source:'Candidate 01; separate preview only'})});
 button.textContent='Exterior model saved';button.dataset.saved='true';
 }catch(error){button.textContent='Export failed — retry';console.error(error);}finally{button.disabled=false;}});
try{model=await buildExterior();scene.add(model.root);applyView('arrival');status.hidden=true;}catch(error){status.innerHTML='<strong>The preview could not load</strong><span>Please reload this local preview. '+error.message+'</span>';console.error(error);throw error;}
function updateWalking(dt){let f=Number(keys.has('forward'))-Number(keys.has('back')),s=Number(keys.has('right'))-Number(keys.has('left'));const norm=Math.hypot(f,s)||1;f/=norm;s/=norm;const distance=2.15*dt,dx=(-Math.sin(yaw)*f+Math.cos(yaw)*s)*distance,dz=(-Math.cos(yaw)*f-Math.sin(yaw)*s)*distance;
 // Resolve axes independently for natural wall sliding; dt is capped against tunnelling.
 if(canWalk(position.x+dx,position.z,model.obstacles))position.x+=dx;if(canWalk(position.x,position.z+dz,model.obstacles))position.z+=dz;
 camera.position.copy(position);camera.lookAt(position.x-Math.sin(yaw)*Math.cos(pitch),position.y+Math.sin(pitch),position.z-Math.cos(yaw)*Math.cos(pitch));
 const near=DOORS.find(d=>Math.hypot(position.x-d.x,position.z-d.z)<2);document.querySelector('#place').hidden=!near;if(near){document.querySelector('#place-title').textContent=near.name;document.querySelector('#place-description').textContent=near.description;}}
function render(){requestAnimationFrame(render);const dt=Math.min(last.getDelta(),.05);elapsed+=dt;if(walking)updateWalking(dt);else controls.update();renderer.info.reset();if(document.querySelector('#quality').value==='high')composer.render();else renderer.render(scene,camera);frameCount++;const now=performance.now();if(now-frameStart>1000){fps=Math.round(frameCount*1000/(now-frameStart));frameCount=0;frameStart=now;document.querySelector('#stats').textContent=`Actual 3D candidate · ${renderer.info.render.triangles.toLocaleString()} rendered triangles/frame including lighting passes · ${renderer.info.render.calls} draws · ${fps} fps in this browser. Original ECC crest. Reused approved planting. Exterior exploration only; activities and live integration remain separate.`;}
 // Readable diagnostics support repeatable local verification without mutating the live game.
 canvas.dataset.ready='true';canvas.dataset.mode=walking?'walk':'orbit';canvas.dataset.position=position.toArray().map(v=>v.toFixed(2)).join(',');canvas.dataset.triangles=String(renderer.info.render.triangles);canvas.dataset.draws=String(renderer.info.render.calls);canvas.dataset.fps=String(fps);}
render();
